//
//  RushtonTurbineGUIDemo.swift
//
//
//  Created by Niall Ó Broin on 26/03/2020.
//
@testable import tdGeometryRushtonTurbineLib

func getTurbineTestData() -> RushtonTurbine {
    let rushtonTurbine = try! RushtonTurbine(json: TurbineTestData)
    return rushtonTurbine
}

let TurbineTestData = """
{
    "tankDiameter":300,
    "tankHeight":300,
    "impeller_start_angle":0,
    "shaft":{
        "radius":8
    },
    "impeller":{
        "1":{
            "blades":{
                "innerRadius":25,
                "top":20,
                "bladeThickness":4,
                "outerRadius":50,
                "bottom":71
            },
            "uav":0.10000000149011612,
            "blade_tip_angular_vel_w0":0.0058823530562222004,
            "impeller_position":150,
            "disk":{
                "top":4,
                "bottom":68,
                "radius":37
            },
            "numBlades":6,
            "firstBladeOffset":0,
            "hub":{
                "top":20,
                "bottom":71,
                "radius":16
            }
        },
        "2":{
            "blades":{
                "innerRadius":25,
                "top":20,
                "bladeThickness":4,
                "outerRadius":50,
                "bottom":71
            },
            "uav":0.10000000149011612,
            "blade_tip_angular_vel_w0":0.0058823530562222004,
            "impeller_position":225,
            "disk":{
                "top":4,
                "bottom":68,
                "radius":37
            },
            "numBlades":68,
            "firstBladeOffset":0,
            "hub":{
                "top":20,
                "bottom":71,
                "radius":16
            }
        },
        "0":{
            "blades":{
                "innerRadius":25,
                "top":240,
                "bladeThickness":4,
                "outerRadius":50,
                "bottom":71
            },
            "uav":0.10000000149011612,
            "blade_tip_angular_vel_w0":0.0058823530562222004,
            "impeller_position":75,
            "disk":{
                "top":4,
                "bottom":68,
                "radius":37
            },
            "numBlades":6,
            "firstBladeOffset":0,
            "hub":{
                "top":20,
                "bottom":71,
                "radius":16
            }
        }
    },
    "gridx":300,
    "impeller_startup_steps_until_normal_speed":0,
    "baffles":{
        "firstBaffleOffset":0.78539818525314331,
        "innerRadius":120,
        "thickness":4,
        "numBaffles":4,
        "outerRadius":150
    },
    "numImpellers":3,
    "starting_step":0,
    "name":"GeometryConfig",
    "resolution":0.69999998807907104
}
"""
