cc_test(
  name = "tests",
  srcs = ["RushtonTurbineTest.cpp"],
  deps = [
          "//Sources/tdLBGeometryRushtonTurbineLibCPP:tdLBGeometryRushtonTurbineLib",
          "@googletest//:gtest_main"
  ],
  copts = ["-ISources/tdLBGeometryRushtonTurbineLibCPP"]
)